# Generated by Django 5.0.6 on 2024-06-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
